import pe from 'parse-error'
import { Item } from '../models/item'

if (!global._babelPolyfill) {
  require('babel-polyfill')
}

export const getById = async ({ pathParameters: { id } }, context, callback) => {
  const [err, item] = await to(Item.get({ id }))

  if (err) {
    callback(null, handleErr(err))
  } else {
    const response = {
      statusCode: 200,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(item)
    }

    console.log(` => Item retreived [${item.id}]`)
    callback(null, response)
  }
}

// *** Error handling support in promises
const to = promise =>
  promise
    .then(data => [null, data])
    .catch(err => [pe(err)])

const handleErr = (error, statusCode = 500) => {
  console.error(' => ERROR:', error.stack)

  return {
    statusCode,
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ error })
  }
}
